apiVersion: v1
kind: Pod
metadata:
  name: adminer
  labels:
    app.kubernetes.io/name: adminer
spec:
  containers:
    - name: adminer
      image: adminer
      resources:
        requests:
          memory: "14Mi"
          cpu: "30m"
        limits:
          memory: "512Mi"
          cpu: "500m"
---
kind: Service
apiVersion: v1
metadata:
  name: adminer
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: adminer
  ports:
    - name: http
      port: 8080
      targetPort: 8080
