apiVersion: v1
kind: Pod
metadata:
  name: developer-app
  labels:
    app.kubernetes.io/name: developer-app
    admission.datadoghq.com/enabled: "true"
    tags.datadoghq.com/service: developer-app
    pipsquack.com/cost-centre: cc001
  annotations:
    admission.datadoghq.com/java-lib.version: latest
spec:
  containers:
  - name: developer-app
    image: yaalexf/developer-app@yaalexf/developer-app@sha256:6d725dced5f572baf4c4e87618686739dc575ddb9dc446eecb60f82cc3a7856b
    imagePullPolicy: Always
    env:
    - name: DD_IAST_ENABLED
      value: "true"
    - name: DD_PROFILING_ENABLED
      value: "true"
    - name: DD_DYNAMIC_INSTRUMENTATION_ENABLED
      value: "true"
    - name: DD_DATA_STREAMS_ENABLED
      value: "true"
    # https://docs.datadoghq.com/database_monitoring/connect_dbm_and_apm/?tab=java#setup
    - name: DD_DBM_PROPAGATION_MODE
      value: full
    - name: JAVA_TOOL_OPTIONS
      value: -Ddd.integration.jdbc-datasource.enabled=true
    - name: "DD_JMXFETCH_TOMCAT_ENABLED"
      value: "true"
    # https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.metrics.export.statsd
    - name: MANAGEMENT_OTLP_METRICS_EXPORT_ENABLED
      value: "false"
    - name: MANAGEMENT_STATSD_METRICS_EXPORT_FLAVOR
      value: datadog
    - name: MANAGEMENT_STATSD_METRICS_EXPORT_PROTOCOL
      value: UDS_DATAGRAM
    - name: MANAGEMENT_STATSD_METRICS_EXPORT_HOST
      value: /var/run/datadog/dsd.socket

    # https://docs.datadoghq.com/tracing/guide/inferred-service-opt-in/?tab=java#apm-tracer-configuration
    - name: DD_TRACE_REMOVE_INTEGRATION_SERVICE_NAMES_ENABLED
      value: "true"
    resources:
      limits: {}
