name: CI

on:
  push:
    paths-ignore:
      - '.vscode/**'
      - '**.md'
      - 'kubernetes/**'
      - 'service.datadog.yaml'
      - 'static-analysis.datadog.yml'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Datadog datadog-ci
        run: npm install -g @datadog/datadog-ci
      - name: Tag Pipeline
        env:
          DATADOG_SITE: datadoghq.com
          DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
        run: datadog-ci tag --level pipeline --tags team:developer-app
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7
      - name: Build with Gradle
        env:
          GRADLE_OPTS: "-Dorg.gradle.daemon=false"
        run: ./gradlew bootJar
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        env:
          BUILD: ${{ github.run_id }}
          GIT_COMMIT_SHA: ${{ github.sha }}
          GIT_URL: ${{ github.repositoryUrl }}
          GIT_BRANCH: ${{ github.ref_name }}
        run: |
          docker buildx build --push -t yaalexf/developer-app:${GIT_BRANCH} \
          --platform linux/amd64,linux/arm64 \
          --build-arg BUILD=${BUILD} \
          --build-arg GIT_COMMIT_SHA=${GIT_COMMIT_SHA} \
          --build-arg GIT_URL=${GIT_URL} \
          -f docker/Dockerfile .