name: foo

on:
  workflow_dispatch:
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          ENV_CONTEXT: ${{ toJson(env) }}
        run: |
          echo "$GITHUB_CONTEXT"
          echo "$ENV_CONTEXT"          
      - name: Docker environement
        env:
          BUILD: ${{ github.run_id }}
          GIT_COMMIT_SHA: ${{ github.sha }}
          GIT_URL: ${{ github.repositoryUrl }}
          GIT_BRANCH: ${{ github.ref_name }}
        run: |
          docker pull yaalexf/developer-app:${GIT_BRANCH}
          docker inspect yaalexf/developer-app:${GIT_BRANCH} -f json
          jq
          gh
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

