name: foo

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: yaalexf/developer-app:${{ github.ref_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Docker environement
        run: |
          docker pull ${IMAGE_NAME}
          export DIGEST=$(docker inspect ${IMAGE_NAME} -f json | jq -r '.[0] | .RepoDigests | .[0]')
          cd /home/runner/work/developer-app/developer-app/kubernetes
          sed -ie "s/image: yaalexf.*/${DIGEST/\//\\/}/" developer-app.yaml
          git config user.name "${{ github.workflow }} workflow"
          git config user.email "${GIT_EMAIL}"
          git add developer-app.yaml
          git commit -m "GitHub Actions run ${{ github.run_id }}"
          git push
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: 
          ENV_CONTEXT: ${{ toJson(vars) }}
        run: |
          echo "${{ toJson(github) }}"
          echo "$ENV_CONTEXT"          
