name: foo

on:
  workflow_dispatch:
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          ENV_CONTEXT: ${{ toJson(vars) }}
          USER_CONTEXT: ${{ toJson(user) }}
        run: |
          echo "$GITHUB_CONTEXT"
          echo "$ENV_CONTEXT"          
          echo "$USER_CONTEXT"          
      - name: Docker environement
        env:
          BUILD: ${{ github.run_id }}
          GIT_COMMIT_SHA: ${{ github.sha }}
          GIT_URL: ${{ github.repositoryUrl }}
          GIT_BRANCH: ${{ github.ref_name }}
          RUN_ID: ${{ github.run_id }}
          WORKFLOW_NAME:  ${{ github.workflow }
          GIT_EMAIL: "someone@somewhere.com"
        run: |
          docker pull yaalexf/developer-app:${GIT_BRANCH}
          export DIGEST=$(docker inspect yaalexf/developer-app:argocd -f json | jq -r '.[0] | .RepoDigests | .[0]')
          cd /home/runner/work/developer-app/developer-app/kubernetes
          sed -ie "s/image: yaalexf.*/${DIGEST/\//\\/}/" developer-app.yaml
          git config user.name "${WORKFLOW_NAME} workflow"
          git config user.email "${GIT_EMAIL}"
          git add developer-app.yaml
          git commit -m "GitHub Actions run ${RUN_ID}"
          git push
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

